spring:
  datasource:
    url: 'jdbc:postgresql://localhost:5432/postgres'
    username: 'postgres'
    password: 'ajsah'
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
  flyway:
    baseline-on-migrate: true
app:
  jwtSecret: "SecretKeyForJWTs"
  jwtExpirationInMs: 864_000_000